version: '3.3'

services:
  location_monitor:
    build: .
    command: python3 cloudflare_monitor.py
    env_file:
      - .env
    volumes:
      - ./data:/app/data:rw
    restart: unless-stopped
    user: "1001:1001"
    security_opt:
      - no-new-privileges:true

  incident_monitor:
    build: .
    command: python3 incident_monitor.py
    env_file:
      - .env
    volumes:
      - ./data:/app/data:rw
    restart: unless-stopped
    user: "1001:1001"
    security_opt:
      - no-new-privileges:true